---
title: "重测数据"
author: "郑元瑞"
date: "5/16/2021"
output: html_document
---
```{r}
rm(list = ls()) 
library(tidyverse)
```
读数据并且合并
```{r}
## 读数据并且合并
filenames <- list.files("/Users/zhengyuanrui/Desktop/重测/", pattern = "*.csv", full.names = T)
data <- list()
for(i in seq_along(filenames)){
  data[[i]] <- read.csv(filenames[i], stringsAsFactors = F)
}
df <- do.call(rbind, data)
str(df)

filenames <- list.files("/Users/zhengyuanrui/Desktop/重测2/", pattern = "*.csv", full.names = T)
data <- list()
for(i in seq_along(filenames)){
  data[[i]] <- read.csv(filenames[i], stringsAsFactors = F)
}
df2 <- do.call(rbind, data)

df3 = df %>% select(rt, accuracy, TimeStamp, Subject, NumberOfExper, Name,
              Sex, BirthYear, Education, EducationEn, StiGroup, 
              MatchKey, MisMatchKey, Shape, ShapeName, Label, LabelName,
              ShapeMeaning, Correctkey, Match, test_part, trial, block, block_id,
              trial_id, block_type, trial_type_num, key_press)
df4 = bind_rows(df3, df2)
df4 %>% group_by(Subject) %>% summarise(n = n())
```
将需要的数组转换为 integer
```{r}
# 将需要的数组转换为 integer
df4$rt[df4$rt != "null"] <- as.integer(df4$rt[df4$rt != "null"])
```


```{r}
# 计算基本信息
df4.basic <- df4 %>% 
  dplyr::select(Subject, Sex, BirthYear, Education) %>% 
  dplyr::distinct(Subject, Sex, BirthYear) %>% 
  dplyr::summarise(subj_N = length(Subject),
                   female_N = sum(Sex == 'female'),
                   male_N = sum(Sex == 'male'),
                   Age_mean = round(mean(2021 - BirthYear),2),
                   Age_sd   = round(sd(2021 - BirthYear),2)
  )
```

不符合要求的被试
```{r}
subj_excld_list = df4 %>% mutate(
    acc = case_when(
      accuracy == "false"| accuracy == "FALSE" ~0,
      accuracy == "true"| accuracy == "TRUE"~ 1
  )
) %>% filter(block_type == "test") %>% 
  group_by(Subject) %>% 
  summarise(meanACC = mean(acc))%>%
  dplyr::filter(meanACC <= 0.6) %>%
  dplyr::pull(Subject)
# will exclude one participant
```
invalide trials
```{r}
# invalide trials
num_invalid_trial <- df4 %>% 
  dplyr::filter(block_type == "test") %>%                   # exclude practice trials
  dplyr::filter(!(subj_excld_list %in% subj_excld_list)) %>%       # exclude invalid participant
  dplyr::filter(rt <= 200) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::pull(n)
```

ratio of invalid trials
```{r}
# ratio of invalid trials
num_invalid_trial_ratio <- df4 %>% 
  dplyr::filter(block_type == "test") %>%                   # exclude practice trials
  dplyr::filter(!(Subject %in% subj_excld_list)) %>%   # exclude invalid participant
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(ratio = num_invalid_trial/n)
```

计算dprime
```{r}
df.OL.Dprime <- df4 %>% mutate(
  acc = case_when(
    accuracy == "false"| accuracy == "FALSE" ~0,
    accuracy == "true"| accuracy == "TRUE"~ 1
  )) %>% 
  dplyr::filter(block_type == "test") %>%                   # exclude practice trials
  dplyr::filter(!(Subject %in% subj_excld_list)) %>%       # exclude invalid participant
  dplyr::filter(rt >= 200) %>%                              # exclude very short response
  dplyr::select(Subject, Match, ShapeMeaning, acc) %>% 
  mutate(
    hit = ifelse(acc == 1& Match == "Match", 1, 0), # hit
    cr = ifelse(acc == 1 & Match != "Match", 1, 0),# correct rejection
    miss = ifelse(acc == 0 & Match == "Match", 1, 0),   # miss
    fa = ifelse(acc == 0 & Match != "Match", 1, 0)# false alarm
  )%>% 
  dplyr::group_by(
    Subject, ShapeMeaning
  ) %>% 
dplyr::summarise(
  # rt = mean(as.integer(rt), na.rm = T),
  hit = sum(hit),
  fa = sum(fa),
  miss = sum(miss),
  cr = sum(cr)
) %>% 
  dplyr::mutate(
    hitP = ifelse(hit / (hit + miss) < 1 & hit / (hit + miss) > 0, 
                  hit / (hit + miss), 
                  1 - 1/(2 * (hit + miss))),
    faP = ifelse(fa / (fa + cr) > 0 & fa / (fa + cr) < 1, 
                 fa / (fa + cr), 
                 1/(2 * (fa + cr))),
    dPrime = qnorm(hitP) - qnorm(faP)
  )
# write_csv(df.OL.Dprime, "df.OL.Dprime.csv")
getwd()
sum(is.na(df.OL.Dprime))
```
 计算分组平均RT时间
```{r}
# 计算分组平均RT时间
df.OL.RT <- df4 %>%  mutate(
  acc = case_when(
    accuracy == "false"| accuracy == "FALSE" ~0,
    accuracy == "true"| accuracy == "TRUE"~ 1
  )) %>% 
  dplyr::filter(block_type == "test") %>%                   # exclude practice trials
  dplyr::filter(!(Subject %in% subj_excld_list)) %>%       # exclude invalid participant
  dplyr::filter(rt >= 200) %>%                              # exclude very short response
  dplyr::filter(acc == 1) %>%
  dplyr::group_by(
    Subject, ShapeMeaning, Match
  ) %>% 
  dplyr::summarise(
    rt = mean(as.integer(rt), na.rm = T)
  )
# write_csv(df.OL.RT, "df.OL.RT.csv")
```

开始传统的重复测量方差分析
```{r}
# 开始传统的重复测量方差分析
str(df.OL.Dprime)
df.OL.Dprime$Subject = as.factor(df.OL.Dprime$Subject)
df.OL.Dprime$ShapeMeaning = as.factor(df.OL.Dprime$ShapeMeaning)
df.OL.RT$Subject = as.factor(df.OL.RT$Subject)
df.OL.RT$ShapeMeaning = as.factor(df.OL.RT$ShapeMeaning)
df.OL.RT$Match = as.factor(df.OL.RT$Match)
library(ez)
# dprime重复测量
ezANOVA(df.OL.Dprime, dv = dPrime, wid = Subject, 
                        within = ShapeMeaning, type = 3, detailed = T)
resultDprime <- aov(dPrime ~ ShapeMeaning + Error(Subject/(ShapeMeaning)), df.OL.Dprime) %>% 
  summary()

#rt重复测量
ezANOVA(df.OL.RT, dv = rt, wid = Subject,
                     within = .(ShapeMeaning, Match), type = 3, detailed = T)

resultRT <-  aov(rt ~ ShapeMeaning * Match + Error(Subject/(ShapeMeaning + Match)), df.OL.RT) %>% 
  summary()
```
贝叶斯的分析
```{r}
# 贝叶斯的分析
library(BayesFactor)
df.OL.RT.By <- as.data.frame(df.OL.RT)
df.OL.RT.By$Subject <- factor(df.OL.RT.By$Subject)
df.OL.RT.By$ShapeMeaning <- factor(df.OL.RT.By$ShapeMeaning)
df.OL.RT.By$Match <- factor(df.OL.RT.By$Match)
str(df.OL.RT.By)
df.OL.RT.ByResult = anovaBF(rt ~ ShapeMeaning * Match + Subject, data = df.OL.RT.By, 
                            whichRandom="Subject")
plot(df.OL.RT.ByResult)
## Dprime
df.OL.Dprime.By <- as.data.frame(df.OL.Dprime)

df.OL.Dprime.By$Subject <- factor(df.OL.Dprime.By$Subject)
df.OL.Dprime.By$ShapeMeaning <- factor(df.OL.Dprime.By$ShapeMeaning)
str(df.OL.Dprime.By)
df.OL.Dprime.ByResult = anovaBF(dPrime ~ ShapeMeaning + Subject, data = df.OL.Dprime.By, 
                                whichRandom="Subject")
plot(df.OL.Dprime.ByResult)
```


```{r}
# plot the data
df.rt <- df.OL.RT %>%       
  dplyr::rename(Subject = Subject,
                Matchness = Match,
                RT_m = rt, 
                Valence = ShapeMeaning) %>%
  dplyr::mutate(Valence = ifelse(Valence == "good",  'Good', 
                                 ifelse(Valence == 'bad', 'Bad', 'Neutral')))
df.d <- df.OL.Dprime %>%
  dplyr::rename(Subject = Subject,
                Valence = ShapeMeaning,
                dprime = dPrime) %>%
  dplyr::mutate(Valence = ifelse(Valence == "good",  'Good', 
                                 ifelse(Valence == 'bad', 'Bad', 'Neutral')))



Val_plot_NHST <- function(df.rt, df.d){
  df.plot <- df.rt %>%
    dplyr::filter(Matchness == 'Match') %>%  # select matching data for plotting only.
    dplyr::rename(RT = RT_m) %>%
    dplyr::full_join(., df.d) %>%  
    tidyr::pivot_longer(., cols = c(RT, dprime), 
                        names_to = 'DVs', 
                        values_to = "value") %>% # to longer format
    dplyr::mutate(Valence =factor(Valence, levels = c('Good','Neutral', 'Bad')),
                  DVs = factor(DVs, levels = c('RT', 'dprime')),
                  # create an extra column for ploting the individual data cross different conditions.
                  Conds = ifelse(Valence == 'Good', 1, 
                                 ifelse(Valence == 'Neutral', 2, 3))
                  # Conds = mosaic::derivedFactor("1" = (Valence == 'Good'), 
                  #                               "2" = (Valence == 'Neutral'),
                  #                               "3" = (Valence == 'Bad'),
                  #                               method ="first", .default = NA),
                  # Conds = as.numeric(as.character(Conds)),
    ) 
  
  df.plot$Conds_j <- jitter(df.plot$Conds, amount=.09) # add gitter to x
  
  # New facet label names for panel variable
  # https://stackoverflow.com/questions/34040376/cannot-italicize-facet-labels-with-labeller-label-parsed
  levels(df.plot$DVs ) <- c("RT"=expression(paste("Reaction ", "times (ms)")),
                            "dprime"=expression(paste(italic("d"), ' prime')))
  levels(df.plot$DVs ) <- c("RT"=expression(paste("Reaction ", "times (ms)")),
                            "dprime"=expression(paste(italic("d"), ' prime')))
  
  df.plot.sum_p <- df.plot  %>% 
    dplyr::group_by(Valence,DVs) %>%
    dplyr::summarise(mean = mean(value),
                     sd = sd(value),
                     n = n()) %>%
    dplyr::mutate(se = sd/sqrt(n)) %>%
    dplyr::rename(value = mean) %>%
    dplyr::mutate(Val_num = ifelse(Valence == 'Good', 1,
                                   ifelse(Valence == 'Neutral', 2, 3)))
  
  # df.plot.sum_p <- summarySE(df.plot, measurevar = "value", groupvars = c('Valence',"DVs")) %>%
  #       dplyr::mutate(Val_num = ifelse(Valence == 'Good', 1,
  #                                      ifelse(Valence == 'Neutral', 2, 3)))
  
  pd1 <- position_dodge(0.5)
  scaleFUN <- function(x) sprintf("%.2f", x)
  scales_y <- list(
    RT = scale_y_continuous(limits = c(400, 900)),
    dprime = scale_y_continuous(labels=scaleFUN)
  )
  
  p_df_sum <- df.plot  %>% # dplyr::filter(DVs== 'RT') %>%
    ggplot(., aes(x = Valence, y = value, colour = as.factor(Valence))) +
    geom_line(aes(x = Conds_j, y = value, group = Subject),         # link individual's points by transparent grey lines
              linetype = 1, size = 0.8, colour = "#000000", alpha = 0.06) + 
    geom_point(aes(x = Conds_j, y = value, group = Subject),   # plot individual points
               colour = "#000000",
               size = 3, shape = 20, alpha = 0.1) +
    geom_line(data = df.plot.sum_p, aes(x = as.numeric(Valence), # plot the group means  
                                        y = value, 
                                        #group = Identity, 
                                        colour = as.factor(Valence),
    ), 
    linetype = 1, position = pd1, size = 2)+
    geom_point(data = df.plot.sum_p, aes(x = as.numeric(Valence), # group mean
                                         y = value, 
                                         #group = Identity, 
                                         colour = as.factor(Valence),
    ), 
    shape = 18, position = pd1, size = 5) +
    geom_errorbar(data = df.plot.sum_p, aes(x = as.numeric(Valence),  # group error bar.
                                            y = value, # group = Identity, 
                                            colour = as.factor(Valence),
                                            ymin = value- 1.96*se, 
                                            ymax = value+ 1.96*se), 
                  width = .05, position = pd1, size = 2, alpha = 0.75) +
    scale_colour_brewer(palette = "Dark2") +
    scale_x_continuous(breaks=c(1, 2, 3),
                       labels=c("Good", "Neutral", "Bad")) +
    scale_fill_brewer(palette = "Dark2") +
    #ggtitle("A. Matching task") +
    theme_bw()+
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank(),
          text=element_text(family='Times'),
          legend.title=element_blank(),
          #legend.text = element_text(size =6),
          legend.text = element_blank(),
          legend.position = 'none',
          plot.title = element_text(lineheight=.8, face="bold", size = 18, margin=margin(0,0,20,0)),
          axis.text = element_text (size = 8, color = 'black'),
          axis.title = element_text (size = 8),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.line.x = element_line(color='black', size = 1),    # increase the size of font
          axis.line.y = element_line(color='black', size = 1),    # increase the size of font
          strip.text = element_text (size = 6, color = 'black'),  # size of text in strips, face = "bold"
          panel.spacing = unit(1.5, "lines")
    ) +
    facet_wrap( ~ DVs,
                scales = "free_y", nrow = 1,
                labeller = label_parsed)
  return(p_df_sum)
}
plot <- Val_plot_NHST(df.rt, df.d)
plot
```

















